### ISSUE TITLE
Commercial license

### ISSUE THREAD

**Issue by spiegelball** [adobe-research/MagicFixup#1]
Hey Team,
is it possible to obtain a commercial license for this great project?

**Comment by HadiZayer** [comment]
Hi! Unfortunately it is not possible to get a commercial license due to Adobe Research policy. However, all of the training code is up and it is possible to fully reproduce the model on an open source video dataset.
The model training needs 8 A100 GPUs for 3 days, so it is fairly efficient when compared to similar models training times/GPU requirements
